# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'

target 'lbry' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lbry
  pod 'React', :path => '../app/node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTText'
  ]
  pod 'yoga', :path => '../app/node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps
  pod 'DoubleConversion', :podspec => '../app/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../app/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../app/node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'react-native-video', :podspec => '../app/node_modules/react-native-video/react-native-video.podspec'
end
